# Generated by Django 3.1.6 on 2021-02-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210207_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='dtg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
