# Generated by Django 3.1.6 on 2021-02-07 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210207_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='items',
            field=models.ManyToManyField(to='main_app.Item'),
        ),
        migrations.AddField(
            model_name='cover',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('APP', 'Apps and Sides'), ('ENT', 'Entree'), ('DES', 'Dessert'), ('SOS', 'Soups and Salads'), ('SPE', 'Special'), ('DNK', 'Soft Drink'), ('BAR', 'Bar Drink')], default='non', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='grat15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='grat18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='grat20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
