# Generated by Django 3.1.6 on 2021-02-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210207_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='subtot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='table',
            name='grat15',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='grat18',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='table',
            name='grat20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
