# Generated by Django 3.1.6 on 2021-02-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210207_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cover',
            name='table',
        ),
        migrations.AddField(
            model_name='table',
            name='covers',
            field=models.ManyToManyField(to='main_app.Cover'),
        ),
        migrations.AlterField(
            model_name='cover',
            name='subtot',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
