# Generated by Django 3.1.6 on 2021-02-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_order_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
