# Generated by Django 3.1.6 on 2021-02-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210207_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='subtot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
