# Generated by Django 3.1.6 on 2021-02-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_table_subtot'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
